#!/bin/bash

# ./rc make
# ./rc make clean
# ./rc run ls
# ./rc make test mutex

PIN_ROOT="/home/ltl/src/pin-3.2-81205-gcc-linux"

THIS_DIR=$(cd "$(dirname "$0")"; pwd)
PREDIR=`pwd`

IFEELLUCKY="-ifeellucky"

cd $THIS_DIR

if [ $1 = "make" ]; then
	make -C test ${@:2}
	make PIN_ROOT=${PIN_ROOT} ${@:2}
elif [ $1 = "run" ]; then
	${PIN_ROOT}/pin $IFEELLUCKY -t obj-intel64/pin_locks.so -- ${@:2}
elif [ $1 = "test" ]; then
	${PIN_ROOT}/pin $IFEELLUCKY -t obj-intel64/pin_locks.so -- ./test/${@:2}
fi

cd $PREDIR
